<?php

namespace Database\Factories;

use App\Models\Process;
use App\Models\SubProcess;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<SubProcess>
 */
class SubProcessFactory extends Factory
{
    protected $model = SubProcess::class;

    /**
     * Define the model's default state.
     *
     * The real code ({PROCESS}-P0N) is generated by SubProcessService on create;
     * this factory default is only a stand-in for fixtures built directly.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'process_id' => Process::factory(),
            'code' => strtoupper(fake()->unique()->lexify('???')).'-P01',
            'name_es' => fake()->words(2, true),
            'name_en' => fake()->words(2, true),
            'order_index' => 1,
            'bpmn_xml_es' => null,
            'bpmn_xml_en' => null,
        ];
    }

    /**
     * Attach a BPMN diagram so the resource's has_bpmn flag is true.
     */
    public function withBpmn(): static
    {
        return $this->state(fn (array $attributes) => [
            'bpmn_xml_es' => '<?xml version="1.0"?><definitions/>',
        ]);
    }
}
