<?php

namespace Database\Factories;

use App\Models\SubProcess;
use App\Models\SubSubProcess;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<SubSubProcess>
 */
class SubSubProcessFactory extends Factory
{
    protected $model = SubSubProcess::class;

    /**
     * Define the model's default state.
     *
     * The real code ({SUBPROCESS}-S0N) is generated by SubSubProcessService on
     * create; this factory default is only a stand-in for direct fixtures.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'sub_process_id' => SubProcess::factory(),
            'code' => strtoupper(fake()->unique()->lexify('???')).'-P01-S01',
            'name_es' => fake()->words(2, true),
            'name_en' => fake()->words(2, true),
            'order_index' => 1,
            'bpmn_xml_es' => null,
            'bpmn_xml_en' => null,
        ];
    }

    /**
     * Attach a BPMN diagram so the resource's has_bpmn flag is true.
     */
    public function withBpmn(): static
    {
        return $this->state(fn (array $attributes) => [
            'bpmn_xml_es' => '<?xml version="1.0"?><definitions/>',
        ]);
    }
}
