<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Inventory movements — records every stock change for audit purposes.
     *
     * type='in'         → stock received (purchase, production)
     * type='out'        → stock consumed or sold
     * type='adjustment' → manual correction (e.g. after physical count)
     *
     * journal_entry_id is auto-generated by InventoryMovementService
     * and links the stock movement to the corresponding GL entry.
     */
    public function up(): void
    {
        Schema::create('inventory_movements', function (Blueprint $table) {
            $table->id();

            $table->foreignId('item_id')
                ->constrained('inventory_items')
                ->cascadeOnDelete();

            $table->string('type', 20)->comment('in | out | adjustment');

            $table->decimal('quantity', 10, 2);
            $table->decimal('unit_cost', 15, 2)->nullable()
                ->comment('Cost per unit at the time of movement');

            // Auto-generated GL entry for this movement
            $table->foreignId('journal_entry_id')
                ->nullable()
                ->constrained('journal_entries')
                ->nullOnDelete();

            $table->text('notes')->nullable();

            $table->foreignId('created_by')
                ->constrained('users')
                ->restrictOnDelete();

            $table->timestamps();

            $table->index(['item_id', 'type']);
            $table->index('created_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('inventory_movements');
    }
};
