name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U laravel"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
    - uses: actions/checkout@v4
    - name: Copy .env
      working-directory: backend
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: backend
      env:
        COMPOSER_AUTH: '{}'
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      working-directory: backend
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: backend
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      working-directory: backend
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: laravel_test
        DB_USERNAME: laravel
        DB_PASSWORD: secret
      run: php artisan test
